services:
  backend:
    build: .
    container_name: darmavoz_backend
    restart: always
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - daoos_kit_default

networks:
  daoos_kit_default:
    external: true
