"""sprint 6 fix models order_items

Revision ID: 14efde470349
Revises: ff52d162bc37
Create Date: 2026-05-15 15:48:15.662300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14efde470349'
down_revision: Union[str, None] = 'ff52d162bc37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=True))
    
    # Fill existing rows with 0.0 before making it NOT NULL
    op.execute("UPDATE orders SET total_amount = 0.0")
    op.alter_column('orders', 'total_amount', nullable=False)
    
    op.drop_column('orders', 'material')
    op.drop_column('orders', 'volume')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('material', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('orders', 'total_amount')
    op.drop_table('order_items')
    # ### end Alembic commands ###
