"""Sprint 4: AI analysis and order drafts

Revision ID: 55272814af85
Revises: 670a6cc92c4c
Create Date: 2026-04-28 21:21:22.958591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55272814af85'
down_revision: Union[str, None] = '670a6cc92c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_ai_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('dialogue_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.Column('normalized_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogues.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('source_dialogue_id', sa.UUID(), nullable=True))
    op.alter_column('orders', 'material',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('orders', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'orders', 'dialogues', ['source_dialogue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('orders', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('orders', 'material',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('orders', 'source_dialogue_id')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'source')
    op.drop_table('message_ai_analyses')
    # ### end Alembic commands ###
