"""Fix Client model for Avito integration

Revision ID: 670a6cc92c4c
Revises: 848dde945e0a
Create Date: 2026-04-24 20:01:49.545492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670a6cc92c4c'
down_revision: Union[str, None] = '848dde945e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('external_source', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('external_user_id', sa.String(length=255), nullable=True))
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint('uq_client_ext_source_id', 'clients', ['external_source', 'external_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_ext_source_id', 'clients', type_='unique')
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('clients', 'external_user_id')
    op.drop_column('clients', 'external_source')
    # ### end Alembic commands ###
