"""Sprint 7: Delivery options

Revision ID: 6ca28260f60d
Revises: 14efde470349
Create Date: 2026-05-22 09:42:44.699320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca28260f60d'
down_revision: Union[str, None] = '14efde470349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capacity_m3', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('delivery_option_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'delivery_options', ['delivery_option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_option_id')
    op.drop_table('delivery_options')
    # ### end Alembic commands ###
